language: node_js

node_js:
- "6.0"
- "5.0"
- "4.1"
- "4.0"
- "0.12"
- "0.11"
- "0.10"
- "0.8"
- "0.7"
- "0.5"
- "0.4"
- "0.3"
- "0.2"
- "0.1"
branches:
only:
- master
- dev

install:
- npm install
- npm install fis3 --registry=https://registry.npm.taobao.org
- ./node_modules/fis3/bin/fis release -d ./output
script:
- npm run test
