language: node_js

node_js:
- "6.0"
- "5.0"
- "4.1"
- "4.0"
- "0.12"
- "0.11"
- "0.10"
- "0.8"
- "0.7"
- "0.5"
- "0.4"
- "0.3"
- "0.2"
- "0.1"
branches:
only:
- master
- dev

install:
- sudo npm install fis3 -g
- npm install
- fis3 release -d ./output
script:
- npm run test
